# _config.yml
title: ""
description: "A blog styled like Lainchan with a dark, neon vibe."
baseurl: ""          # leave empty if the site is at the root URL
url: "https://Lxsoftroxs.github.io"  # change to your site URL
