name: Notify Subscribers

on:
  push:
    paths:
      - "_posts/**"
      - "assets/images/**"
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install msmtp
        run: sudo apt-get install msmtp jq -y

      - name: Configure msmtp
        run: |
          echo "account default
          host smtp.gmail.com
          port 587
          auth on
          tls on
          tls_starttls on
          user ${{ secrets.EMAIL_USER }}
          password ${{ secrets.EMAIL_PASS }}
          from ${{ secrets.EMAIL_USER }}" > ~/.msmtprc
          chmod 600 ~/.msmtprc

      - name: Fetch subscribers
        run: |
          if [ -f subscribers.json ]; then
            emails=$(jq -r '.[]' subscribers.json | paste -sd, -)
            echo "EMAIL_LIST=$emails" >> $GITHUB_ENV
          else
            echo "EMAIL_LIST=" >> $GITHUB_ENV
          fi

      - name: Get latest post details
        run: |
          POST=$(ls -t _posts | head -n1)
          TITLE=$(grep -m1 "^title:" "_posts/$POST" | sed 's/title: //')
          URL="https://lxsoftroxs.github.io/$(basename "$POST" .md)/"
          echo "POST_TITLE=$TITLE" >> $GITHUB_ENV
          echo "POST_URL=$URL" >> $GITHUB_ENV

      - name: Send notification email
        run: |
          SUBJECT="New Post: '${{ env.POST_TITLE }}'"
          BODY="Check out the new post: '${{ env.POST_TITLE }}'
          ${{ env.POST_URL }}"
          echo -e "Subject: ${SUBJECT}\n\n${BODY}" | msmtp -a default ${{ env.EMAIL_LIST }}
