name: Notify Subscribers of New Content

on:
  push:
    paths:
      - "_posts/**"
      - "assets/images/**"  # If you want to trigger on new photos as well
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install msmtp and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp msmtp-mta jq

      - name: Configure msmtp
        run: |
          cat <<EOF > ~/.msmtprc
          account default
          host smtp.gmail.com
          port 587
          auth on
          tls on
          tls_starttls on
          user ${{ secrets.EMAIL_USER }}
          password ${{ secrets.EMAIL_PASS }}
          from ${{ secrets.EMAIL_USER }}
          logfile ~/.msmtp.log
          EOF
          chmod 600 ~/.msmtprc

      - name: Fetch subscribers
        run: |
          if [ -f subscribers.json ]; then
            emails=$(jq -r '.[]' subscribers.json | paste -sd, -)
            echo "EMAIL_LIST=$emails" >> $GITHUB_ENV
          else
            echo "EMAIL_LIST=" >> $GITHUB_ENV
          fi
      - name: Get latest post details
        run: |
          POST_FILE=$(ls -t _posts | head -n1)  # Get the latest post filename
          TITLE=$(grep -m1 "^title:" "_posts/$POST_FILE" | sed 's/title: //')  # Extract title
          SLUG=$(basename "$POST_FILE" .md | cut -d'-' -f4-)  # Extract slug from filename
          URL="https://lxsoftroxs.github.io/${SLUG}.html"  # Construct correct post URL

          echo "POST_TITLE=$TITLE" >> $GITHUB_ENV
          echo "POST_URL=$URL" >> $GITHUB_ENV

      - name: Send notification email
        run: |
          cat <<EOF | msmtp -a default "${{ env.EMAIL_LIST }}"
          Subject: New Post: "${{ env.POST_TITLE }}"

          Check out the new post: "${{ env.POST_TITLE }}"
          ${{ env.POST_URL }}
          EOF


